version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: crypto_coffee
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: always

volumes:
  mariadb-data: