spring:
  # DB Setting
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: 'jdbc:mariadb://localhost:3306/crypto_coffee'
    username: root
    password: kwak8174
  # JPA Setting
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
  # JWT Setting
  jwt:
    secret: 'abcavavavasvadwaefhaekudbuevfukwedfykaseygfukywbedkuyhbakdugfeakfyhbdjkcbukayegwgvfi'

# Spring DOC
springdoc:
  swagger-ui:
    operations-sorter: alpha
    display-request-duration: true
    disable-swagger-default-url: true
